@baseUrl = http://localhost:8080

### Get All Carbon Inventories
GET {{baseUrl}}/api/carbon-inventories HTTP/1.1


### Get Carbon Inventory by ID
GET {{baseUrl}}/api/carbon-inventories/1 HTTP/1.1


### Create Carbon Inventory - Minimal (SIMPLIFIED inventory)
POST {{baseUrl}}/api/carbon-inventories HTTP/1.1
Content-Type: application/json

{
  "usageMode": "SIMPLIFIED"
}


### Create Carbon Inventory - EXPERT mode
POST {{baseUrl}}/api/carbon-inventories HTTP/1.1
Content-Type: application/json

{
  "usageMode": "EXPERT"
}


### Update Carbon Inventory - Update all fields
PATCH {{baseUrl}}/api/carbon-inventories/1 HTTP/1.1
Content-Type: application/json

{
  "organizationId": "1",
  "organizationBranchId": "1",
  "organizationData": {
    "name": "Updated Organization",
    "sectorId": "2",
    "subsectorId": "3",
    "sizeId": "1",
    "mainActivityId": "1",
    "mainActivityQuantity": 100
  },
  "year": 2024,
  "usageMode": "SIMPLIFIED",
  "preselectedNodesId": "1",
  "status": "DRAFT",
  "isEditable": true
}


### Update Carbon Inventory - Partial update (only year and usageMode)
PATCH {{baseUrl}}/api/carbon-inventories/1 HTTP/1.1
Content-Type: application/json

{
  "year": 2024,
  "usageMode": "EXPERT"
}


### Update Carbon Inventory - Set nullable fields to null
PATCH {{baseUrl}}/api/carbon-inventories/1 HTTP/1.1
Content-Type: application/json

{
  "organizationId": null,
  "organizationBranchId": null,
  "organizationData": null,
  "year": null,
  "preselectedNodesId": null
}


### Update Carbon Inventory - Update organization data only
PATCH {{baseUrl}}/api/carbon-inventories/1 HTTP/1.1
Content-Type: application/json

{
  "organizationData": {
    "name": "My Company",
    "sectorId": "1",
    "subsectorId": "1",
    "sizeId": "2",
    "mainActivityId": "3",
    "mainActivityQuantity": 50
  }
}


### Update Carbon Inventory - Update status
PATCH {{baseUrl}}/api/carbon-inventories/1 HTTP/1.1
Content-Type: application/json

{
  "status": "SUBMITTED"
}


### Update Carbon Inventory Lines - Use Case 1: Empty line (all null)
PATCH {{baseUrl}}/api/carbon-inventories/1/lines HTTP/1.1
Content-Type: application/json

[
  {
    "id": "1",
    "dimensionValue1Id": null,
    "dimensionValue2Id": null,
    "measurementUnitId": null,
    "quantity": null,
    "factorSource": null,
    "baseFactorId": null,
    "appliedFactorValue": null,
    "appliedFactorRateMeasurementUnitId": null,
    "manualTotalEmissions": null,
    "comment": null
  }
]


### Update Carbon Inventory Lines - Use Case 2: Manual total emissions (DIRECT mode)
PATCH {{baseUrl}}/api/carbon-inventories/1/lines HTTP/1.1
Content-Type: application/json

[
  {
    "id": "1",
    "dimensionValue1Id": null,
    "dimensionValue2Id": null,
    "measurementUnitId": null,
    "quantity": null,
    "factorSource": null,
    "baseFactorId": null,
    "appliedFactorValue": null,
    "appliedFactorRateMeasurementUnitId": null,
    "manualTotalEmissions": 500000,
    "comment": null
  }
]


### Update Carbon Inventory Lines - Use Case 3: Automatic factor (SIMPLIFIED inventory, DETAILED line type)
PATCH {{baseUrl}}/api/carbon-inventories/1/lines HTTP/1.1
Content-Type: application/json

[
  {
    "id": "3",
    "dimensionValue1Id": "2",
    "dimensionValue2Id": "8",
    "measurementUnitId": "5",
    "quantity": 1500,
    "factorSource": "DEFRA 2025",
    "baseFactorId": "3",
    "appliedFactorValue": 2.57,
    "appliedFactorRateMeasurementUnitId": "7",
    "manualTotalEmissions": null,
    "comment": "Consumo mensual de gas natural en calderas"
  }
]


### Update Carbon Inventory Lines - Use Case 4: Manual factor (EXPERT mode)
PATCH {{baseUrl}}/api/carbon-inventories/1/lines HTTP/1.1
Content-Type: application/json

[
  {
    "id": "1",
    "dimensionValue1Id": "2",
    "dimensionValue2Id": "8",
    "measurementUnitId": "5",
    "quantity": 1500,
    "factorSource": "Factor Propio",
    "baseFactorId": null,
    "appliedFactorValue": 2.999,
    "appliedFactorRateMeasurementUnitId": "7",
    "manualTotalEmissions": null,
    "comment": "Consumo mensual de gas natural en calderas"
  }
]


### Update Carbon Inventory Lines - Multiple lines at once
PATCH {{baseUrl}}/api/carbon-inventories/1/lines HTTP/1.1
Content-Type: application/json

[
  {
    "id": "1",
    "dimensionValue1Id": null,
    "dimensionValue2Id": null,
    "measurementUnitId": null,
    "quantity": null,
    "factorSource": null,
    "baseFactorId": null,
    "appliedFactorValue": null,
    "appliedFactorRateMeasurementUnitId": null,
    "manualTotalEmissions": null,
    "comment": null
  },
  {
    "id": "2",
    "dimensionValue1Id": null,
    "dimensionValue2Id": null,
    "measurementUnitId": null,
    "quantity": null,
    "factorSource": null,
    "baseFactorId": null,
    "appliedFactorValue": null,
    "appliedFactorRateMeasurementUnitId": null,
    "manualTotalEmissions": 500000,
    "comment": null
  }
]

