@baseUrl = http://localhost:8080

### Get All Measurement Units
GET {{baseUrl}}/api/measurement-units HTTP/1.1


### Get All Rate Measurement Units
GET {{baseUrl}}/api/measurement-units/rates HTTP/1.1
