@baseUrl = http://localhost:8080

### Create User
POST {{baseUrl}}/api/users HTTP/1.1
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "firstName": "John",
    "lastName": "Doe",
    "countryJobPositionId": "1"
}


### Get All Users
GET {{baseUrl}}/api/users HTTP/1.1


### Get User by ID
GET {{baseUrl}}/api/users/1 HTTP/1.1


### Update User - Update Email
PATCH {{baseUrl}}/api/users/1 HTTP/1.1
Content-Type: application/json

{
    "email": "newemail@example.com"
}


### Update User - Update Job Position
PATCH {{baseUrl}}/api/users/1 HTTP/1.1
Content-Type: application/json

{
    "countryJobPositionId": "3"
}


### Update User - Update Names
PATCH {{baseUrl}}/api/users/1 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Don",
    "lastName": "Joe"
}


### Update User - Update All Fields
PATCH {{baseUrl}}/api/users/1 HTTP/1.1
Content-Type: application/json

{
    "email": "updated@example.com",
    "countryJobPositionId": "2",
    "firstName": "Updated",
    "lastName": "User"
}


### Delete User
DELETE {{baseUrl}}/api/users/1 HTTP/1.1
