@baseUrl = http://localhost:8080

### Create User
POST {{baseUrl}}/api/users HTTP/1.1
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "firstName": "John",
    "lastName": "Doe",
    "countryJobPositionId": "1"
}


### Get All Users
GET {{baseUrl}}/api/users HTTP/1.1


### Get User by ID
GET {{baseUrl}}/api/users/1 HTTP/1.1

