/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as CapinautRouteImport } from './routes/capinaut'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReductionProjectsRouteImport } from './routes/app/reduction-projects'
import { Route as AppReductionPlanRouteImport } from './routes/app/reduction-plan'
import { Route as AppMyOrganizationRouteImport } from './routes/app/my-organization'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppCarbonInventoryRouteImport } from './routes/app/carbon-inventory'
import { Route as AppCarbonInventoriesRouteImport } from './routes/app/carbon-inventories'
import { Route as AppAwardsRouteImport } from './routes/app/awards'
import { Route as AdminUnitsRouteImport } from './routes/admin/units'
import { Route as AdminSubcategoriesRouteImport } from './routes/admin/subcategories'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminParametersRouteImport } from './routes/admin/parameters'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminMethodologiesRouteImport } from './routes/admin/methodologies'
import { Route as AdminMainActivitiesRouteImport } from './routes/admin/main-activities'
import { Route as AdminItemsRouteImport } from './routes/admin/items'
import { Route as AdminEmissionFactorsRouteImport } from './routes/admin/emission-factors'
import { Route as AdminDimensionsRouteImport } from './routes/admin/dimensions'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AppCarbonInventoryIndexRouteImport } from './routes/app/carbon-inventory/index'
import { Route as AppUserFormRouteImport } from './routes/app/user/form'
import { Route as AppCarbonInventoryInventoryIdSubcategoryPreselectionRouteImport } from './routes/app/carbon-inventory/$inventoryId/subcategory-preselection'
import { Route as AppCarbonInventoryInventoryIdEmissionSummaryRouteImport } from './routes/app/carbon-inventory/$inventoryId/emission-summary'
import { Route as AppCarbonInventoryInventoryIdEmissionResultsRouteImport } from './routes/app/carbon-inventory/$inventoryId/emission-results'
import { Route as AppCarbonInventoryInventoryIdEmissionCaptureRouteImport } from './routes/app/carbon-inventory/$inventoryId/emission-capture'
import { Route as AppCarbonInventoryInventoryIdBusinessProfilingRouteImport } from './routes/app/carbon-inventory/$inventoryId/business-profiling'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const CapinautRoute = CapinautRouteImport.update({
  id: '/capinaut',
  path: '/capinaut',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReductionProjectsRoute = AppReductionProjectsRouteImport.update({
  id: '/app/reduction-projects',
  path: '/app/reduction-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReductionPlanRoute = AppReductionPlanRouteImport.update({
  id: '/app/reduction-plan',
  path: '/app/reduction-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMyOrganizationRoute = AppMyOrganizationRouteImport.update({
  id: '/app/my-organization',
  path: '/app/my-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCarbonInventoryRoute = AppCarbonInventoryRouteImport.update({
  id: '/app/carbon-inventory',
  path: '/app/carbon-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCarbonInventoriesRoute = AppCarbonInventoriesRouteImport.update({
  id: '/app/carbon-inventories',
  path: '/app/carbon-inventories',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAwardsRoute = AppAwardsRouteImport.update({
  id: '/app/awards',
  path: '/app/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnitsRoute = AdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubcategoriesRoute = AdminSubcategoriesRouteImport.update({
  id: '/subcategories',
  path: '/subcategories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametersRoute = AdminParametersRouteImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMethodologiesRoute = AdminMethodologiesRouteImport.update({
  id: '/methodologies',
  path: '/methodologies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMainActivitiesRoute = AdminMainActivitiesRouteImport.update({
  id: '/main-activities',
  path: '/main-activities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmissionFactorsRoute = AdminEmissionFactorsRouteImport.update({
  id: '/emission-factors',
  path: '/emission-factors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDimensionsRoute = AdminDimensionsRouteImport.update({
  id: '/dimensions',
  path: '/dimensions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AppCarbonInventoryIndexRoute = AppCarbonInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCarbonInventoryRoute,
} as any)
const AppUserFormRoute = AppUserFormRouteImport.update({
  id: '/app/user/form',
  path: '/app/user/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCarbonInventoryInventoryIdSubcategoryPreselectionRoute =
  AppCarbonInventoryInventoryIdSubcategoryPreselectionRouteImport.update({
    id: '/$inventoryId/subcategory-preselection',
    path: '/$inventoryId/subcategory-preselection',
    getParentRoute: () => AppCarbonInventoryRoute,
  } as any)
const AppCarbonInventoryInventoryIdEmissionSummaryRoute =
  AppCarbonInventoryInventoryIdEmissionSummaryRouteImport.update({
    id: '/$inventoryId/emission-summary',
    path: '/$inventoryId/emission-summary',
    getParentRoute: () => AppCarbonInventoryRoute,
  } as any)
const AppCarbonInventoryInventoryIdEmissionResultsRoute =
  AppCarbonInventoryInventoryIdEmissionResultsRouteImport.update({
    id: '/$inventoryId/emission-results',
    path: '/$inventoryId/emission-results',
    getParentRoute: () => AppCarbonInventoryRoute,
  } as any)
const AppCarbonInventoryInventoryIdEmissionCaptureRoute =
  AppCarbonInventoryInventoryIdEmissionCaptureRouteImport.update({
    id: '/$inventoryId/emission-capture',
    path: '/$inventoryId/emission-capture',
    getParentRoute: () => AppCarbonInventoryRoute,
  } as any)
const AppCarbonInventoryInventoryIdBusinessProfilingRoute =
  AppCarbonInventoryInventoryIdBusinessProfilingRouteImport.update({
    id: '/$inventoryId/business-profiling',
    path: '/$inventoryId/business-profiling',
    getParentRoute: () => AppCarbonInventoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/capinaut': typeof CapinautRoute
  '/transparency': typeof TransparencyRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dimensions': typeof AdminDimensionsRoute
  '/admin/emission-factors': typeof AdminEmissionFactorsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/main-activities': typeof AdminMainActivitiesRoute
  '/admin/methodologies': typeof AdminMethodologiesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/parameters': typeof AdminParametersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/units': typeof AdminUnitsRoute
  '/app/awards': typeof AppAwardsRoute
  '/app/carbon-inventories': typeof AppCarbonInventoriesRoute
  '/app/carbon-inventory': typeof AppCarbonInventoryRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/my-organization': typeof AppMyOrganizationRoute
  '/app/reduction-plan': typeof AppReductionPlanRoute
  '/app/reduction-projects': typeof AppReductionProjectsRoute
  '/app/user/form': typeof AppUserFormRoute
  '/app/carbon-inventory/': typeof AppCarbonInventoryIndexRoute
  '/app/carbon-inventory/$inventoryId/business-profiling': typeof AppCarbonInventoryInventoryIdBusinessProfilingRoute
  '/app/carbon-inventory/$inventoryId/emission-capture': typeof AppCarbonInventoryInventoryIdEmissionCaptureRoute
  '/app/carbon-inventory/$inventoryId/emission-results': typeof AppCarbonInventoryInventoryIdEmissionResultsRoute
  '/app/carbon-inventory/$inventoryId/emission-summary': typeof AppCarbonInventoryInventoryIdEmissionSummaryRoute
  '/app/carbon-inventory/$inventoryId/subcategory-preselection': typeof AppCarbonInventoryInventoryIdSubcategoryPreselectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/capinaut': typeof CapinautRoute
  '/transparency': typeof TransparencyRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dimensions': typeof AdminDimensionsRoute
  '/admin/emission-factors': typeof AdminEmissionFactorsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/main-activities': typeof AdminMainActivitiesRoute
  '/admin/methodologies': typeof AdminMethodologiesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/parameters': typeof AdminParametersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/units': typeof AdminUnitsRoute
  '/app/awards': typeof AppAwardsRoute
  '/app/carbon-inventories': typeof AppCarbonInventoriesRoute
  '/app/home': typeof AppHomeRoute
  '/app/my-organization': typeof AppMyOrganizationRoute
  '/app/reduction-plan': typeof AppReductionPlanRoute
  '/app/reduction-projects': typeof AppReductionProjectsRoute
  '/app/user/form': typeof AppUserFormRoute
  '/app/carbon-inventory': typeof AppCarbonInventoryIndexRoute
  '/app/carbon-inventory/$inventoryId/business-profiling': typeof AppCarbonInventoryInventoryIdBusinessProfilingRoute
  '/app/carbon-inventory/$inventoryId/emission-capture': typeof AppCarbonInventoryInventoryIdEmissionCaptureRoute
  '/app/carbon-inventory/$inventoryId/emission-results': typeof AppCarbonInventoryInventoryIdEmissionResultsRoute
  '/app/carbon-inventory/$inventoryId/emission-summary': typeof AppCarbonInventoryInventoryIdEmissionSummaryRoute
  '/app/carbon-inventory/$inventoryId/subcategory-preselection': typeof AppCarbonInventoryInventoryIdSubcategoryPreselectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/capinaut': typeof CapinautRoute
  '/transparency': typeof TransparencyRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dimensions': typeof AdminDimensionsRoute
  '/admin/emission-factors': typeof AdminEmissionFactorsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/main-activities': typeof AdminMainActivitiesRoute
  '/admin/methodologies': typeof AdminMethodologiesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/parameters': typeof AdminParametersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/units': typeof AdminUnitsRoute
  '/app/awards': typeof AppAwardsRoute
  '/app/carbon-inventories': typeof AppCarbonInventoriesRoute
  '/app/carbon-inventory': typeof AppCarbonInventoryRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/my-organization': typeof AppMyOrganizationRoute
  '/app/reduction-plan': typeof AppReductionPlanRoute
  '/app/reduction-projects': typeof AppReductionProjectsRoute
  '/app/user/form': typeof AppUserFormRoute
  '/app/carbon-inventory/': typeof AppCarbonInventoryIndexRoute
  '/app/carbon-inventory/$inventoryId/business-profiling': typeof AppCarbonInventoryInventoryIdBusinessProfilingRoute
  '/app/carbon-inventory/$inventoryId/emission-capture': typeof AppCarbonInventoryInventoryIdEmissionCaptureRoute
  '/app/carbon-inventory/$inventoryId/emission-results': typeof AppCarbonInventoryInventoryIdEmissionResultsRoute
  '/app/carbon-inventory/$inventoryId/emission-summary': typeof AppCarbonInventoryInventoryIdEmissionSummaryRoute
  '/app/carbon-inventory/$inventoryId/subcategory-preselection': typeof AppCarbonInventoryInventoryIdSubcategoryPreselectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/capinaut'
    | '/transparency'
    | '/admin/categories'
    | '/admin/dimensions'
    | '/admin/emission-factors'
    | '/admin/items'
    | '/admin/main-activities'
    | '/admin/methodologies'
    | '/admin/organizations'
    | '/admin/parameters'
    | '/admin/requests'
    | '/admin/subcategories'
    | '/admin/units'
    | '/app/awards'
    | '/app/carbon-inventories'
    | '/app/carbon-inventory'
    | '/app/home'
    | '/app/my-organization'
    | '/app/reduction-plan'
    | '/app/reduction-projects'
    | '/app/user/form'
    | '/app/carbon-inventory/'
    | '/app/carbon-inventory/$inventoryId/business-profiling'
    | '/app/carbon-inventory/$inventoryId/emission-capture'
    | '/app/carbon-inventory/$inventoryId/emission-results'
    | '/app/carbon-inventory/$inventoryId/emission-summary'
    | '/app/carbon-inventory/$inventoryId/subcategory-preselection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/capinaut'
    | '/transparency'
    | '/admin/categories'
    | '/admin/dimensions'
    | '/admin/emission-factors'
    | '/admin/items'
    | '/admin/main-activities'
    | '/admin/methodologies'
    | '/admin/organizations'
    | '/admin/parameters'
    | '/admin/requests'
    | '/admin/subcategories'
    | '/admin/units'
    | '/app/awards'
    | '/app/carbon-inventories'
    | '/app/home'
    | '/app/my-organization'
    | '/app/reduction-plan'
    | '/app/reduction-projects'
    | '/app/user/form'
    | '/app/carbon-inventory'
    | '/app/carbon-inventory/$inventoryId/business-profiling'
    | '/app/carbon-inventory/$inventoryId/emission-capture'
    | '/app/carbon-inventory/$inventoryId/emission-results'
    | '/app/carbon-inventory/$inventoryId/emission-summary'
    | '/app/carbon-inventory/$inventoryId/subcategory-preselection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/capinaut'
    | '/transparency'
    | '/admin/categories'
    | '/admin/dimensions'
    | '/admin/emission-factors'
    | '/admin/items'
    | '/admin/main-activities'
    | '/admin/methodologies'
    | '/admin/organizations'
    | '/admin/parameters'
    | '/admin/requests'
    | '/admin/subcategories'
    | '/admin/units'
    | '/app/awards'
    | '/app/carbon-inventories'
    | '/app/carbon-inventory'
    | '/app/home'
    | '/app/my-organization'
    | '/app/reduction-plan'
    | '/app/reduction-projects'
    | '/app/user/form'
    | '/app/carbon-inventory/'
    | '/app/carbon-inventory/$inventoryId/business-profiling'
    | '/app/carbon-inventory/$inventoryId/emission-capture'
    | '/app/carbon-inventory/$inventoryId/emission-results'
    | '/app/carbon-inventory/$inventoryId/emission-summary'
    | '/app/carbon-inventory/$inventoryId/subcategory-preselection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CapinautRoute: typeof CapinautRoute
  TransparencyRoute: typeof TransparencyRoute
  AppAwardsRoute: typeof AppAwardsRoute
  AppCarbonInventoriesRoute: typeof AppCarbonInventoriesRoute
  AppCarbonInventoryRoute: typeof AppCarbonInventoryRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppMyOrganizationRoute: typeof AppMyOrganizationRoute
  AppReductionPlanRoute: typeof AppReductionPlanRoute
  AppReductionProjectsRoute: typeof AppReductionProjectsRoute
  AppUserFormRoute: typeof AppUserFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capinaut': {
      id: '/capinaut'
      path: '/capinaut'
      fullPath: '/capinaut'
      preLoaderRoute: typeof CapinautRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reduction-projects': {
      id: '/app/reduction-projects'
      path: '/app/reduction-projects'
      fullPath: '/app/reduction-projects'
      preLoaderRoute: typeof AppReductionProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reduction-plan': {
      id: '/app/reduction-plan'
      path: '/app/reduction-plan'
      fullPath: '/app/reduction-plan'
      preLoaderRoute: typeof AppReductionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/my-organization': {
      id: '/app/my-organization'
      path: '/app/my-organization'
      fullPath: '/app/my-organization'
      preLoaderRoute: typeof AppMyOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/carbon-inventory': {
      id: '/app/carbon-inventory'
      path: '/app/carbon-inventory'
      fullPath: '/app/carbon-inventory'
      preLoaderRoute: typeof AppCarbonInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/carbon-inventories': {
      id: '/app/carbon-inventories'
      path: '/app/carbon-inventories'
      fullPath: '/app/carbon-inventories'
      preLoaderRoute: typeof AppCarbonInventoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/awards': {
      id: '/app/awards'
      path: '/app/awards'
      fullPath: '/app/awards'
      preLoaderRoute: typeof AppAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/units': {
      id: '/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AdminUnitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcategories': {
      id: '/admin/subcategories'
      path: '/subcategories'
      fullPath: '/admin/subcategories'
      preLoaderRoute: typeof AdminSubcategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parameters': {
      id: '/admin/parameters'
      path: '/parameters'
      fullPath: '/admin/parameters'
      preLoaderRoute: typeof AdminParametersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/methodologies': {
      id: '/admin/methodologies'
      path: '/methodologies'
      fullPath: '/admin/methodologies'
      preLoaderRoute: typeof AdminMethodologiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/main-activities': {
      id: '/admin/main-activities'
      path: '/main-activities'
      fullPath: '/admin/main-activities'
      preLoaderRoute: typeof AdminMainActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emission-factors': {
      id: '/admin/emission-factors'
      path: '/emission-factors'
      fullPath: '/admin/emission-factors'
      preLoaderRoute: typeof AdminEmissionFactorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dimensions': {
      id: '/admin/dimensions'
      path: '/dimensions'
      fullPath: '/admin/dimensions'
      preLoaderRoute: typeof AdminDimensionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/carbon-inventory/': {
      id: '/app/carbon-inventory/'
      path: '/'
      fullPath: '/app/carbon-inventory/'
      preLoaderRoute: typeof AppCarbonInventoryIndexRouteImport
      parentRoute: typeof AppCarbonInventoryRoute
    }
    '/app/user/form': {
      id: '/app/user/form'
      path: '/app/user/form'
      fullPath: '/app/user/form'
      preLoaderRoute: typeof AppUserFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/carbon-inventory/$inventoryId/subcategory-preselection': {
      id: '/app/carbon-inventory/$inventoryId/subcategory-preselection'
      path: '/$inventoryId/subcategory-preselection'
      fullPath: '/app/carbon-inventory/$inventoryId/subcategory-preselection'
      preLoaderRoute: typeof AppCarbonInventoryInventoryIdSubcategoryPreselectionRouteImport
      parentRoute: typeof AppCarbonInventoryRoute
    }
    '/app/carbon-inventory/$inventoryId/emission-summary': {
      id: '/app/carbon-inventory/$inventoryId/emission-summary'
      path: '/$inventoryId/emission-summary'
      fullPath: '/app/carbon-inventory/$inventoryId/emission-summary'
      preLoaderRoute: typeof AppCarbonInventoryInventoryIdEmissionSummaryRouteImport
      parentRoute: typeof AppCarbonInventoryRoute
    }
    '/app/carbon-inventory/$inventoryId/emission-results': {
      id: '/app/carbon-inventory/$inventoryId/emission-results'
      path: '/$inventoryId/emission-results'
      fullPath: '/app/carbon-inventory/$inventoryId/emission-results'
      preLoaderRoute: typeof AppCarbonInventoryInventoryIdEmissionResultsRouteImport
      parentRoute: typeof AppCarbonInventoryRoute
    }
    '/app/carbon-inventory/$inventoryId/emission-capture': {
      id: '/app/carbon-inventory/$inventoryId/emission-capture'
      path: '/$inventoryId/emission-capture'
      fullPath: '/app/carbon-inventory/$inventoryId/emission-capture'
      preLoaderRoute: typeof AppCarbonInventoryInventoryIdEmissionCaptureRouteImport
      parentRoute: typeof AppCarbonInventoryRoute
    }
    '/app/carbon-inventory/$inventoryId/business-profiling': {
      id: '/app/carbon-inventory/$inventoryId/business-profiling'
      path: '/$inventoryId/business-profiling'
      fullPath: '/app/carbon-inventory/$inventoryId/business-profiling'
      preLoaderRoute: typeof AppCarbonInventoryInventoryIdBusinessProfilingRouteImport
      parentRoute: typeof AppCarbonInventoryRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDimensionsRoute: typeof AdminDimensionsRoute
  AdminEmissionFactorsRoute: typeof AdminEmissionFactorsRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminMainActivitiesRoute: typeof AdminMainActivitiesRoute
  AdminMethodologiesRoute: typeof AdminMethodologiesRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminParametersRoute: typeof AdminParametersRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSubcategoriesRoute: typeof AdminSubcategoriesRoute
  AdminUnitsRoute: typeof AdminUnitsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDimensionsRoute: AdminDimensionsRoute,
  AdminEmissionFactorsRoute: AdminEmissionFactorsRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminMainActivitiesRoute: AdminMainActivitiesRoute,
  AdminMethodologiesRoute: AdminMethodologiesRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminParametersRoute: AdminParametersRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSubcategoriesRoute: AdminSubcategoriesRoute,
  AdminUnitsRoute: AdminUnitsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCarbonInventoryRouteChildren {
  AppCarbonInventoryIndexRoute: typeof AppCarbonInventoryIndexRoute
  AppCarbonInventoryInventoryIdBusinessProfilingRoute: typeof AppCarbonInventoryInventoryIdBusinessProfilingRoute
  AppCarbonInventoryInventoryIdEmissionCaptureRoute: typeof AppCarbonInventoryInventoryIdEmissionCaptureRoute
  AppCarbonInventoryInventoryIdEmissionResultsRoute: typeof AppCarbonInventoryInventoryIdEmissionResultsRoute
  AppCarbonInventoryInventoryIdEmissionSummaryRoute: typeof AppCarbonInventoryInventoryIdEmissionSummaryRoute
  AppCarbonInventoryInventoryIdSubcategoryPreselectionRoute: typeof AppCarbonInventoryInventoryIdSubcategoryPreselectionRoute
}

const AppCarbonInventoryRouteChildren: AppCarbonInventoryRouteChildren = {
  AppCarbonInventoryIndexRoute: AppCarbonInventoryIndexRoute,
  AppCarbonInventoryInventoryIdBusinessProfilingRoute:
    AppCarbonInventoryInventoryIdBusinessProfilingRoute,
  AppCarbonInventoryInventoryIdEmissionCaptureRoute:
    AppCarbonInventoryInventoryIdEmissionCaptureRoute,
  AppCarbonInventoryInventoryIdEmissionResultsRoute:
    AppCarbonInventoryInventoryIdEmissionResultsRoute,
  AppCarbonInventoryInventoryIdEmissionSummaryRoute:
    AppCarbonInventoryInventoryIdEmissionSummaryRoute,
  AppCarbonInventoryInventoryIdSubcategoryPreselectionRoute:
    AppCarbonInventoryInventoryIdSubcategoryPreselectionRoute,
}

const AppCarbonInventoryRouteWithChildren =
  AppCarbonInventoryRoute._addFileChildren(AppCarbonInventoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CapinautRoute: CapinautRoute,
  TransparencyRoute: TransparencyRoute,
  AppAwardsRoute: AppAwardsRoute,
  AppCarbonInventoriesRoute: AppCarbonInventoriesRoute,
  AppCarbonInventoryRoute: AppCarbonInventoryRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppMyOrganizationRoute: AppMyOrganizationRoute,
  AppReductionPlanRoute: AppReductionPlanRoute,
  AppReductionProjectsRoute: AppReductionProjectsRoute,
  AppUserFormRoute: AppUserFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
