/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as ReductionProjectsRouteImport } from './routes/reduction-projects'
import { Route as ReductionPlanRouteImport } from './routes/reduction-plan'
import { Route as OrganizationFootprintRouteImport } from './routes/organization-footprint'
import { Route as MyCompanyRouteImport } from './routes/my-company'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CapinautRouteImport } from './routes/capinaut'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const ReductionProjectsRoute = ReductionProjectsRouteImport.update({
  id: '/reduction-projects',
  path: '/reduction-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReductionPlanRoute = ReductionPlanRouteImport.update({
  id: '/reduction-plan',
  path: '/reduction-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationFootprintRoute = OrganizationFootprintRouteImport.update({
  id: '/organization-footprint',
  path: '/organization-footprint',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCompanyRoute = MyCompanyRouteImport.update({
  id: '/my-company',
  path: '/my-company',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CapinautRoute = CapinautRouteImport.update({
  id: '/capinaut',
  path: '/capinaut',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/capinaut': typeof CapinautRoute
  '/home': typeof HomeRoute
  '/my-company': typeof MyCompanyRoute
  '/organization-footprint': typeof OrganizationFootprintRoute
  '/reduction-plan': typeof ReductionPlanRoute
  '/reduction-projects': typeof ReductionProjectsRoute
  '/transparency': typeof TransparencyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/capinaut': typeof CapinautRoute
  '/home': typeof HomeRoute
  '/my-company': typeof MyCompanyRoute
  '/organization-footprint': typeof OrganizationFootprintRoute
  '/reduction-plan': typeof ReductionPlanRoute
  '/reduction-projects': typeof ReductionProjectsRoute
  '/transparency': typeof TransparencyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/capinaut': typeof CapinautRoute
  '/home': typeof HomeRoute
  '/my-company': typeof MyCompanyRoute
  '/organization-footprint': typeof OrganizationFootprintRoute
  '/reduction-plan': typeof ReductionPlanRoute
  '/reduction-projects': typeof ReductionProjectsRoute
  '/transparency': typeof TransparencyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/awards'
    | '/capinaut'
    | '/home'
    | '/my-company'
    | '/organization-footprint'
    | '/reduction-plan'
    | '/reduction-projects'
    | '/transparency'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/awards'
    | '/capinaut'
    | '/home'
    | '/my-company'
    | '/organization-footprint'
    | '/reduction-plan'
    | '/reduction-projects'
    | '/transparency'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/awards'
    | '/capinaut'
    | '/home'
    | '/my-company'
    | '/organization-footprint'
    | '/reduction-plan'
    | '/reduction-projects'
    | '/transparency'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AwardsRoute: typeof AwardsRoute
  CapinautRoute: typeof CapinautRoute
  HomeRoute: typeof HomeRoute
  MyCompanyRoute: typeof MyCompanyRoute
  OrganizationFootprintRoute: typeof OrganizationFootprintRoute
  ReductionPlanRoute: typeof ReductionPlanRoute
  ReductionProjectsRoute: typeof ReductionProjectsRoute
  TransparencyRoute: typeof TransparencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reduction-projects': {
      id: '/reduction-projects'
      path: '/reduction-projects'
      fullPath: '/reduction-projects'
      preLoaderRoute: typeof ReductionProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reduction-plan': {
      id: '/reduction-plan'
      path: '/reduction-plan'
      fullPath: '/reduction-plan'
      preLoaderRoute: typeof ReductionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization-footprint': {
      id: '/organization-footprint'
      path: '/organization-footprint'
      fullPath: '/organization-footprint'
      preLoaderRoute: typeof OrganizationFootprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-company': {
      id: '/my-company'
      path: '/my-company'
      fullPath: '/my-company'
      preLoaderRoute: typeof MyCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capinaut': {
      id: '/capinaut'
      path: '/capinaut'
      fullPath: '/capinaut'
      preLoaderRoute: typeof CapinautRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AwardsRoute: AwardsRoute,
  CapinautRoute: CapinautRoute,
  HomeRoute: HomeRoute,
  MyCompanyRoute: MyCompanyRoute,
  OrganizationFootprintRoute: OrganizationFootprintRoute,
  ReductionPlanRoute: ReductionPlanRoute,
  ReductionProjectsRoute: ReductionProjectsRoute,
  TransparencyRoute: TransparencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
