/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as CarbonInventoryRouteImport } from './routes/carbon-inventory'
import { Route as CapinautRouteImport } from './routes/capinaut'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarbonInventoryIndexRouteImport } from './routes/carbon-inventory/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppReductionProjectsRouteImport } from './routes/app/reduction-projects'
import { Route as AppReductionPlanRouteImport } from './routes/app/reduction-plan'
import { Route as AppRecognitionsRouteImport } from './routes/app/recognitions'
import { Route as AppMyOrganizationRouteImport } from './routes/app/my-organization'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppCarbonInventoriesRouteImport } from './routes/app/carbon-inventories'
import { Route as AdminUnitsRouteImport } from './routes/admin/units'
import { Route as AdminSubsectorsRouteImport } from './routes/admin/subsectors'
import { Route as AdminSubcategoryRecommendationsRouteImport } from './routes/admin/subcategory-recommendations'
import { Route as AdminSubcategoriesRouteImport } from './routes/admin/subcategories'
import { Route as AdminSectorsRouteImport } from './routes/admin/sectors'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminReductionPlanInitiativesRouteImport } from './routes/admin/reduction-plan-initiatives'
import { Route as AdminParametersRouteImport } from './routes/admin/parameters'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminOrganizationSizesRouteImport } from './routes/admin/organization-sizes'
import { Route as AdminMethodologiesRouteImport } from './routes/admin/methodologies'
import { Route as AdminMainActivitiesRouteImport } from './routes/admin/main-activities'
import { Route as AdminExplanationsRouteImport } from './routes/admin/explanations'
import { Route as AdminEmissionFactorsRouteImport } from './routes/admin/emission-factors'
import { Route as AdminDimensionsRouteImport } from './routes/admin/dimensions'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBadgesRouteImport } from './routes/admin/badges'
import { Route as AppReductionProjectsIndexRouteImport } from './routes/app/reduction-projects/index'
import { Route as CarbonInventoryInventoryIdSubcategoryPreselectionRouteImport } from './routes/carbon-inventory/$inventoryId/subcategory-preselection'
import { Route as CarbonInventoryInventoryIdEmissionSummaryRouteImport } from './routes/carbon-inventory/$inventoryId/emission-summary'
import { Route as CarbonInventoryInventoryIdEmissionResultsRouteImport } from './routes/carbon-inventory/$inventoryId/emission-results'
import { Route as CarbonInventoryInventoryIdEmissionCaptureRouteImport } from './routes/carbon-inventory/$inventoryId/emission-capture'
import { Route as CarbonInventoryInventoryIdBusinessProfilingRouteImport } from './routes/carbon-inventory/$inventoryId/business-profiling'
import { Route as AppUserFormRouteImport } from './routes/app/user/form'
import { Route as AppReductionProjectsNewRouteImport } from './routes/app/reduction-projects/new'
import { Route as AppReductionProjectsIdRouteImport } from './routes/app/reduction-projects/$id'
import { Route as AppReductionProjectsIdEditRouteImport } from './routes/app/reduction-projects/$id/edit'
import { Route as AppReductionProjectsIdDetailsRouteImport } from './routes/app/reduction-projects/$id/details'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonInventoryRoute = CarbonInventoryRouteImport.update({
  id: '/carbon-inventory',
  path: '/carbon-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CapinautRoute = CapinautRouteImport.update({
  id: '/capinaut',
  path: '/capinaut',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonInventoryIndexRoute = CarbonInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarbonInventoryRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppReductionProjectsRoute = AppReductionProjectsRouteImport.update({
  id: '/reduction-projects',
  path: '/reduction-projects',
  getParentRoute: () => AppRoute,
} as any)
const AppReductionPlanRoute = AppReductionPlanRouteImport.update({
  id: '/reduction-plan',
  path: '/reduction-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppRecognitionsRoute = AppRecognitionsRouteImport.update({
  id: '/recognitions',
  path: '/recognitions',
  getParentRoute: () => AppRoute,
} as any)
const AppMyOrganizationRoute = AppMyOrganizationRouteImport.update({
  id: '/my-organization',
  path: '/my-organization',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCarbonInventoriesRoute = AppCarbonInventoriesRouteImport.update({
  id: '/carbon-inventories',
  path: '/carbon-inventories',
  getParentRoute: () => AppRoute,
} as any)
const AdminUnitsRoute = AdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubsectorsRoute = AdminSubsectorsRouteImport.update({
  id: '/subsectors',
  path: '/subsectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubcategoryRecommendationsRoute =
  AdminSubcategoryRecommendationsRouteImport.update({
    id: '/subcategory-recommendations',
    path: '/subcategory-recommendations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSubcategoriesRoute = AdminSubcategoriesRouteImport.update({
  id: '/subcategories',
  path: '/subcategories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectorsRoute = AdminSectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReductionPlanInitiativesRoute =
  AdminReductionPlanInitiativesRouteImport.update({
    id: '/reduction-plan-initiatives',
    path: '/reduction-plan-initiatives',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminParametersRoute = AdminParametersRouteImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationSizesRoute = AdminOrganizationSizesRouteImport.update({
  id: '/organization-sizes',
  path: '/organization-sizes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMethodologiesRoute = AdminMethodologiesRouteImport.update({
  id: '/methodologies',
  path: '/methodologies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMainActivitiesRoute = AdminMainActivitiesRouteImport.update({
  id: '/main-activities',
  path: '/main-activities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExplanationsRoute = AdminExplanationsRouteImport.update({
  id: '/explanations',
  path: '/explanations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmissionFactorsRoute = AdminEmissionFactorsRouteImport.update({
  id: '/emission-factors',
  path: '/emission-factors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDimensionsRoute = AdminDimensionsRouteImport.update({
  id: '/dimensions',
  path: '/dimensions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AdminRoute,
} as any)
const AppReductionProjectsIndexRoute =
  AppReductionProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppReductionProjectsRoute,
  } as any)
const CarbonInventoryInventoryIdSubcategoryPreselectionRoute =
  CarbonInventoryInventoryIdSubcategoryPreselectionRouteImport.update({
    id: '/$inventoryId/subcategory-preselection',
    path: '/$inventoryId/subcategory-preselection',
    getParentRoute: () => CarbonInventoryRoute,
  } as any)
const CarbonInventoryInventoryIdEmissionSummaryRoute =
  CarbonInventoryInventoryIdEmissionSummaryRouteImport.update({
    id: '/$inventoryId/emission-summary',
    path: '/$inventoryId/emission-summary',
    getParentRoute: () => CarbonInventoryRoute,
  } as any)
const CarbonInventoryInventoryIdEmissionResultsRoute =
  CarbonInventoryInventoryIdEmissionResultsRouteImport.update({
    id: '/$inventoryId/emission-results',
    path: '/$inventoryId/emission-results',
    getParentRoute: () => CarbonInventoryRoute,
  } as any)
const CarbonInventoryInventoryIdEmissionCaptureRoute =
  CarbonInventoryInventoryIdEmissionCaptureRouteImport.update({
    id: '/$inventoryId/emission-capture',
    path: '/$inventoryId/emission-capture',
    getParentRoute: () => CarbonInventoryRoute,
  } as any)
const CarbonInventoryInventoryIdBusinessProfilingRoute =
  CarbonInventoryInventoryIdBusinessProfilingRouteImport.update({
    id: '/$inventoryId/business-profiling',
    path: '/$inventoryId/business-profiling',
    getParentRoute: () => CarbonInventoryRoute,
  } as any)
const AppUserFormRoute = AppUserFormRouteImport.update({
  id: '/user/form',
  path: '/user/form',
  getParentRoute: () => AppRoute,
} as any)
const AppReductionProjectsNewRoute = AppReductionProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReductionProjectsRoute,
} as any)
const AppReductionProjectsIdRoute = AppReductionProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReductionProjectsRoute,
} as any)
const AppReductionProjectsIdEditRoute =
  AppReductionProjectsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppReductionProjectsIdRoute,
  } as any)
const AppReductionProjectsIdDetailsRoute =
  AppReductionProjectsIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => AppReductionProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/capinaut': typeof CapinautRoute
  '/carbon-inventory': typeof CarbonInventoryRouteWithChildren
  '/transparency': typeof TransparencyRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dimensions': typeof AdminDimensionsRoute
  '/admin/emission-factors': typeof AdminEmissionFactorsRoute
  '/admin/explanations': typeof AdminExplanationsRoute
  '/admin/main-activities': typeof AdminMainActivitiesRoute
  '/admin/methodologies': typeof AdminMethodologiesRoute
  '/admin/organization-sizes': typeof AdminOrganizationSizesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/parameters': typeof AdminParametersRoute
  '/admin/reduction-plan-initiatives': typeof AdminReductionPlanInitiativesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/sectors': typeof AdminSectorsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/subcategory-recommendations': typeof AdminSubcategoryRecommendationsRoute
  '/admin/subsectors': typeof AdminSubsectorsRoute
  '/admin/units': typeof AdminUnitsRoute
  '/app/carbon-inventories': typeof AppCarbonInventoriesRoute
  '/app/home': typeof AppHomeRoute
  '/app/my-organization': typeof AppMyOrganizationRoute
  '/app/recognitions': typeof AppRecognitionsRoute
  '/app/reduction-plan': typeof AppReductionPlanRoute
  '/app/reduction-projects': typeof AppReductionProjectsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/carbon-inventory/': typeof CarbonInventoryIndexRoute
  '/app/reduction-projects/$id': typeof AppReductionProjectsIdRouteWithChildren
  '/app/reduction-projects/new': typeof AppReductionProjectsNewRoute
  '/app/user/form': typeof AppUserFormRoute
  '/carbon-inventory/$inventoryId/business-profiling': typeof CarbonInventoryInventoryIdBusinessProfilingRoute
  '/carbon-inventory/$inventoryId/emission-capture': typeof CarbonInventoryInventoryIdEmissionCaptureRoute
  '/carbon-inventory/$inventoryId/emission-results': typeof CarbonInventoryInventoryIdEmissionResultsRoute
  '/carbon-inventory/$inventoryId/emission-summary': typeof CarbonInventoryInventoryIdEmissionSummaryRoute
  '/carbon-inventory/$inventoryId/subcategory-preselection': typeof CarbonInventoryInventoryIdSubcategoryPreselectionRoute
  '/app/reduction-projects/': typeof AppReductionProjectsIndexRoute
  '/app/reduction-projects/$id/details': typeof AppReductionProjectsIdDetailsRoute
  '/app/reduction-projects/$id/edit': typeof AppReductionProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capinaut': typeof CapinautRoute
  '/transparency': typeof TransparencyRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dimensions': typeof AdminDimensionsRoute
  '/admin/emission-factors': typeof AdminEmissionFactorsRoute
  '/admin/explanations': typeof AdminExplanationsRoute
  '/admin/main-activities': typeof AdminMainActivitiesRoute
  '/admin/methodologies': typeof AdminMethodologiesRoute
  '/admin/organization-sizes': typeof AdminOrganizationSizesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/parameters': typeof AdminParametersRoute
  '/admin/reduction-plan-initiatives': typeof AdminReductionPlanInitiativesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/sectors': typeof AdminSectorsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/subcategory-recommendations': typeof AdminSubcategoryRecommendationsRoute
  '/admin/subsectors': typeof AdminSubsectorsRoute
  '/admin/units': typeof AdminUnitsRoute
  '/app/carbon-inventories': typeof AppCarbonInventoriesRoute
  '/app/home': typeof AppHomeRoute
  '/app/my-organization': typeof AppMyOrganizationRoute
  '/app/recognitions': typeof AppRecognitionsRoute
  '/app/reduction-plan': typeof AppReductionPlanRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/carbon-inventory': typeof CarbonInventoryIndexRoute
  '/app/reduction-projects/$id': typeof AppReductionProjectsIdRouteWithChildren
  '/app/reduction-projects/new': typeof AppReductionProjectsNewRoute
  '/app/user/form': typeof AppUserFormRoute
  '/carbon-inventory/$inventoryId/business-profiling': typeof CarbonInventoryInventoryIdBusinessProfilingRoute
  '/carbon-inventory/$inventoryId/emission-capture': typeof CarbonInventoryInventoryIdEmissionCaptureRoute
  '/carbon-inventory/$inventoryId/emission-results': typeof CarbonInventoryInventoryIdEmissionResultsRoute
  '/carbon-inventory/$inventoryId/emission-summary': typeof CarbonInventoryInventoryIdEmissionSummaryRoute
  '/carbon-inventory/$inventoryId/subcategory-preselection': typeof CarbonInventoryInventoryIdSubcategoryPreselectionRoute
  '/app/reduction-projects': typeof AppReductionProjectsIndexRoute
  '/app/reduction-projects/$id/details': typeof AppReductionProjectsIdDetailsRoute
  '/app/reduction-projects/$id/edit': typeof AppReductionProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/capinaut': typeof CapinautRoute
  '/carbon-inventory': typeof CarbonInventoryRouteWithChildren
  '/transparency': typeof TransparencyRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dimensions': typeof AdminDimensionsRoute
  '/admin/emission-factors': typeof AdminEmissionFactorsRoute
  '/admin/explanations': typeof AdminExplanationsRoute
  '/admin/main-activities': typeof AdminMainActivitiesRoute
  '/admin/methodologies': typeof AdminMethodologiesRoute
  '/admin/organization-sizes': typeof AdminOrganizationSizesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/parameters': typeof AdminParametersRoute
  '/admin/reduction-plan-initiatives': typeof AdminReductionPlanInitiativesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/sectors': typeof AdminSectorsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/subcategory-recommendations': typeof AdminSubcategoryRecommendationsRoute
  '/admin/subsectors': typeof AdminSubsectorsRoute
  '/admin/units': typeof AdminUnitsRoute
  '/app/carbon-inventories': typeof AppCarbonInventoriesRoute
  '/app/home': typeof AppHomeRoute
  '/app/my-organization': typeof AppMyOrganizationRoute
  '/app/recognitions': typeof AppRecognitionsRoute
  '/app/reduction-plan': typeof AppReductionPlanRoute
  '/app/reduction-projects': typeof AppReductionProjectsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/carbon-inventory/': typeof CarbonInventoryIndexRoute
  '/app/reduction-projects/$id': typeof AppReductionProjectsIdRouteWithChildren
  '/app/reduction-projects/new': typeof AppReductionProjectsNewRoute
  '/app/user/form': typeof AppUserFormRoute
  '/carbon-inventory/$inventoryId/business-profiling': typeof CarbonInventoryInventoryIdBusinessProfilingRoute
  '/carbon-inventory/$inventoryId/emission-capture': typeof CarbonInventoryInventoryIdEmissionCaptureRoute
  '/carbon-inventory/$inventoryId/emission-results': typeof CarbonInventoryInventoryIdEmissionResultsRoute
  '/carbon-inventory/$inventoryId/emission-summary': typeof CarbonInventoryInventoryIdEmissionSummaryRoute
  '/carbon-inventory/$inventoryId/subcategory-preselection': typeof CarbonInventoryInventoryIdSubcategoryPreselectionRoute
  '/app/reduction-projects/': typeof AppReductionProjectsIndexRoute
  '/app/reduction-projects/$id/details': typeof AppReductionProjectsIdDetailsRoute
  '/app/reduction-projects/$id/edit': typeof AppReductionProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/capinaut'
    | '/carbon-inventory'
    | '/transparency'
    | '/admin/badges'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/dimensions'
    | '/admin/emission-factors'
    | '/admin/explanations'
    | '/admin/main-activities'
    | '/admin/methodologies'
    | '/admin/organization-sizes'
    | '/admin/organizations'
    | '/admin/parameters'
    | '/admin/reduction-plan-initiatives'
    | '/admin/requests'
    | '/admin/sectors'
    | '/admin/subcategories'
    | '/admin/subcategory-recommendations'
    | '/admin/subsectors'
    | '/admin/units'
    | '/app/carbon-inventories'
    | '/app/home'
    | '/app/my-organization'
    | '/app/recognitions'
    | '/app/reduction-plan'
    | '/app/reduction-projects'
    | '/admin/'
    | '/app/'
    | '/carbon-inventory/'
    | '/app/reduction-projects/$id'
    | '/app/reduction-projects/new'
    | '/app/user/form'
    | '/carbon-inventory/$inventoryId/business-profiling'
    | '/carbon-inventory/$inventoryId/emission-capture'
    | '/carbon-inventory/$inventoryId/emission-results'
    | '/carbon-inventory/$inventoryId/emission-summary'
    | '/carbon-inventory/$inventoryId/subcategory-preselection'
    | '/app/reduction-projects/'
    | '/app/reduction-projects/$id/details'
    | '/app/reduction-projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/capinaut'
    | '/transparency'
    | '/admin/badges'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/dimensions'
    | '/admin/emission-factors'
    | '/admin/explanations'
    | '/admin/main-activities'
    | '/admin/methodologies'
    | '/admin/organization-sizes'
    | '/admin/organizations'
    | '/admin/parameters'
    | '/admin/reduction-plan-initiatives'
    | '/admin/requests'
    | '/admin/sectors'
    | '/admin/subcategories'
    | '/admin/subcategory-recommendations'
    | '/admin/subsectors'
    | '/admin/units'
    | '/app/carbon-inventories'
    | '/app/home'
    | '/app/my-organization'
    | '/app/recognitions'
    | '/app/reduction-plan'
    | '/admin'
    | '/app'
    | '/carbon-inventory'
    | '/app/reduction-projects/$id'
    | '/app/reduction-projects/new'
    | '/app/user/form'
    | '/carbon-inventory/$inventoryId/business-profiling'
    | '/carbon-inventory/$inventoryId/emission-capture'
    | '/carbon-inventory/$inventoryId/emission-results'
    | '/carbon-inventory/$inventoryId/emission-summary'
    | '/carbon-inventory/$inventoryId/subcategory-preselection'
    | '/app/reduction-projects'
    | '/app/reduction-projects/$id/details'
    | '/app/reduction-projects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/capinaut'
    | '/carbon-inventory'
    | '/transparency'
    | '/admin/badges'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/dimensions'
    | '/admin/emission-factors'
    | '/admin/explanations'
    | '/admin/main-activities'
    | '/admin/methodologies'
    | '/admin/organization-sizes'
    | '/admin/organizations'
    | '/admin/parameters'
    | '/admin/reduction-plan-initiatives'
    | '/admin/requests'
    | '/admin/sectors'
    | '/admin/subcategories'
    | '/admin/subcategory-recommendations'
    | '/admin/subsectors'
    | '/admin/units'
    | '/app/carbon-inventories'
    | '/app/home'
    | '/app/my-organization'
    | '/app/recognitions'
    | '/app/reduction-plan'
    | '/app/reduction-projects'
    | '/admin/'
    | '/app/'
    | '/carbon-inventory/'
    | '/app/reduction-projects/$id'
    | '/app/reduction-projects/new'
    | '/app/user/form'
    | '/carbon-inventory/$inventoryId/business-profiling'
    | '/carbon-inventory/$inventoryId/emission-capture'
    | '/carbon-inventory/$inventoryId/emission-results'
    | '/carbon-inventory/$inventoryId/emission-summary'
    | '/carbon-inventory/$inventoryId/subcategory-preselection'
    | '/app/reduction-projects/'
    | '/app/reduction-projects/$id/details'
    | '/app/reduction-projects/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CapinautRoute: typeof CapinautRoute
  CarbonInventoryRoute: typeof CarbonInventoryRouteWithChildren
  TransparencyRoute: typeof TransparencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbon-inventory': {
      id: '/carbon-inventory'
      path: '/carbon-inventory'
      fullPath: '/carbon-inventory'
      preLoaderRoute: typeof CarbonInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capinaut': {
      id: '/capinaut'
      path: '/capinaut'
      fullPath: '/capinaut'
      preLoaderRoute: typeof CapinautRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbon-inventory/': {
      id: '/carbon-inventory/'
      path: '/'
      fullPath: '/carbon-inventory/'
      preLoaderRoute: typeof CarbonInventoryIndexRouteImport
      parentRoute: typeof CarbonInventoryRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/reduction-projects': {
      id: '/app/reduction-projects'
      path: '/reduction-projects'
      fullPath: '/app/reduction-projects'
      preLoaderRoute: typeof AppReductionProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reduction-plan': {
      id: '/app/reduction-plan'
      path: '/reduction-plan'
      fullPath: '/app/reduction-plan'
      preLoaderRoute: typeof AppReductionPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recognitions': {
      id: '/app/recognitions'
      path: '/recognitions'
      fullPath: '/app/recognitions'
      preLoaderRoute: typeof AppRecognitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-organization': {
      id: '/app/my-organization'
      path: '/my-organization'
      fullPath: '/app/my-organization'
      preLoaderRoute: typeof AppMyOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/carbon-inventories': {
      id: '/app/carbon-inventories'
      path: '/carbon-inventories'
      fullPath: '/app/carbon-inventories'
      preLoaderRoute: typeof AppCarbonInventoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/units': {
      id: '/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AdminUnitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subsectors': {
      id: '/admin/subsectors'
      path: '/subsectors'
      fullPath: '/admin/subsectors'
      preLoaderRoute: typeof AdminSubsectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcategory-recommendations': {
      id: '/admin/subcategory-recommendations'
      path: '/subcategory-recommendations'
      fullPath: '/admin/subcategory-recommendations'
      preLoaderRoute: typeof AdminSubcategoryRecommendationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcategories': {
      id: '/admin/subcategories'
      path: '/subcategories'
      fullPath: '/admin/subcategories'
      preLoaderRoute: typeof AdminSubcategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sectors': {
      id: '/admin/sectors'
      path: '/sectors'
      fullPath: '/admin/sectors'
      preLoaderRoute: typeof AdminSectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reduction-plan-initiatives': {
      id: '/admin/reduction-plan-initiatives'
      path: '/reduction-plan-initiatives'
      fullPath: '/admin/reduction-plan-initiatives'
      preLoaderRoute: typeof AdminReductionPlanInitiativesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parameters': {
      id: '/admin/parameters'
      path: '/parameters'
      fullPath: '/admin/parameters'
      preLoaderRoute: typeof AdminParametersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization-sizes': {
      id: '/admin/organization-sizes'
      path: '/organization-sizes'
      fullPath: '/admin/organization-sizes'
      preLoaderRoute: typeof AdminOrganizationSizesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/methodologies': {
      id: '/admin/methodologies'
      path: '/methodologies'
      fullPath: '/admin/methodologies'
      preLoaderRoute: typeof AdminMethodologiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/main-activities': {
      id: '/admin/main-activities'
      path: '/main-activities'
      fullPath: '/admin/main-activities'
      preLoaderRoute: typeof AdminMainActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/explanations': {
      id: '/admin/explanations'
      path: '/explanations'
      fullPath: '/admin/explanations'
      preLoaderRoute: typeof AdminExplanationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emission-factors': {
      id: '/admin/emission-factors'
      path: '/emission-factors'
      fullPath: '/admin/emission-factors'
      preLoaderRoute: typeof AdminEmissionFactorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dimensions': {
      id: '/admin/dimensions'
      path: '/dimensions'
      fullPath: '/admin/dimensions'
      preLoaderRoute: typeof AdminDimensionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/badges': {
      id: '/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/reduction-projects/': {
      id: '/app/reduction-projects/'
      path: '/'
      fullPath: '/app/reduction-projects/'
      preLoaderRoute: typeof AppReductionProjectsIndexRouteImport
      parentRoute: typeof AppReductionProjectsRoute
    }
    '/carbon-inventory/$inventoryId/subcategory-preselection': {
      id: '/carbon-inventory/$inventoryId/subcategory-preselection'
      path: '/$inventoryId/subcategory-preselection'
      fullPath: '/carbon-inventory/$inventoryId/subcategory-preselection'
      preLoaderRoute: typeof CarbonInventoryInventoryIdSubcategoryPreselectionRouteImport
      parentRoute: typeof CarbonInventoryRoute
    }
    '/carbon-inventory/$inventoryId/emission-summary': {
      id: '/carbon-inventory/$inventoryId/emission-summary'
      path: '/$inventoryId/emission-summary'
      fullPath: '/carbon-inventory/$inventoryId/emission-summary'
      preLoaderRoute: typeof CarbonInventoryInventoryIdEmissionSummaryRouteImport
      parentRoute: typeof CarbonInventoryRoute
    }
    '/carbon-inventory/$inventoryId/emission-results': {
      id: '/carbon-inventory/$inventoryId/emission-results'
      path: '/$inventoryId/emission-results'
      fullPath: '/carbon-inventory/$inventoryId/emission-results'
      preLoaderRoute: typeof CarbonInventoryInventoryIdEmissionResultsRouteImport
      parentRoute: typeof CarbonInventoryRoute
    }
    '/carbon-inventory/$inventoryId/emission-capture': {
      id: '/carbon-inventory/$inventoryId/emission-capture'
      path: '/$inventoryId/emission-capture'
      fullPath: '/carbon-inventory/$inventoryId/emission-capture'
      preLoaderRoute: typeof CarbonInventoryInventoryIdEmissionCaptureRouteImport
      parentRoute: typeof CarbonInventoryRoute
    }
    '/carbon-inventory/$inventoryId/business-profiling': {
      id: '/carbon-inventory/$inventoryId/business-profiling'
      path: '/$inventoryId/business-profiling'
      fullPath: '/carbon-inventory/$inventoryId/business-profiling'
      preLoaderRoute: typeof CarbonInventoryInventoryIdBusinessProfilingRouteImport
      parentRoute: typeof CarbonInventoryRoute
    }
    '/app/user/form': {
      id: '/app/user/form'
      path: '/user/form'
      fullPath: '/app/user/form'
      preLoaderRoute: typeof AppUserFormRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reduction-projects/new': {
      id: '/app/reduction-projects/new'
      path: '/new'
      fullPath: '/app/reduction-projects/new'
      preLoaderRoute: typeof AppReductionProjectsNewRouteImport
      parentRoute: typeof AppReductionProjectsRoute
    }
    '/app/reduction-projects/$id': {
      id: '/app/reduction-projects/$id'
      path: '/$id'
      fullPath: '/app/reduction-projects/$id'
      preLoaderRoute: typeof AppReductionProjectsIdRouteImport
      parentRoute: typeof AppReductionProjectsRoute
    }
    '/app/reduction-projects/$id/edit': {
      id: '/app/reduction-projects/$id/edit'
      path: '/edit'
      fullPath: '/app/reduction-projects/$id/edit'
      preLoaderRoute: typeof AppReductionProjectsIdEditRouteImport
      parentRoute: typeof AppReductionProjectsIdRoute
    }
    '/app/reduction-projects/$id/details': {
      id: '/app/reduction-projects/$id/details'
      path: '/details'
      fullPath: '/app/reduction-projects/$id/details'
      preLoaderRoute: typeof AppReductionProjectsIdDetailsRouteImport
      parentRoute: typeof AppReductionProjectsIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDimensionsRoute: typeof AdminDimensionsRoute
  AdminEmissionFactorsRoute: typeof AdminEmissionFactorsRoute
  AdminExplanationsRoute: typeof AdminExplanationsRoute
  AdminMainActivitiesRoute: typeof AdminMainActivitiesRoute
  AdminMethodologiesRoute: typeof AdminMethodologiesRoute
  AdminOrganizationSizesRoute: typeof AdminOrganizationSizesRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminParametersRoute: typeof AdminParametersRoute
  AdminReductionPlanInitiativesRoute: typeof AdminReductionPlanInitiativesRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSectorsRoute: typeof AdminSectorsRoute
  AdminSubcategoriesRoute: typeof AdminSubcategoriesRoute
  AdminSubcategoryRecommendationsRoute: typeof AdminSubcategoryRecommendationsRoute
  AdminSubsectorsRoute: typeof AdminSubsectorsRoute
  AdminUnitsRoute: typeof AdminUnitsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBadgesRoute: AdminBadgesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDimensionsRoute: AdminDimensionsRoute,
  AdminEmissionFactorsRoute: AdminEmissionFactorsRoute,
  AdminExplanationsRoute: AdminExplanationsRoute,
  AdminMainActivitiesRoute: AdminMainActivitiesRoute,
  AdminMethodologiesRoute: AdminMethodologiesRoute,
  AdminOrganizationSizesRoute: AdminOrganizationSizesRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminParametersRoute: AdminParametersRoute,
  AdminReductionPlanInitiativesRoute: AdminReductionPlanInitiativesRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSectorsRoute: AdminSectorsRoute,
  AdminSubcategoriesRoute: AdminSubcategoriesRoute,
  AdminSubcategoryRecommendationsRoute: AdminSubcategoryRecommendationsRoute,
  AdminSubsectorsRoute: AdminSubsectorsRoute,
  AdminUnitsRoute: AdminUnitsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppReductionProjectsIdRouteChildren {
  AppReductionProjectsIdDetailsRoute: typeof AppReductionProjectsIdDetailsRoute
  AppReductionProjectsIdEditRoute: typeof AppReductionProjectsIdEditRoute
}

const AppReductionProjectsIdRouteChildren: AppReductionProjectsIdRouteChildren =
  {
    AppReductionProjectsIdDetailsRoute: AppReductionProjectsIdDetailsRoute,
    AppReductionProjectsIdEditRoute: AppReductionProjectsIdEditRoute,
  }

const AppReductionProjectsIdRouteWithChildren =
  AppReductionProjectsIdRoute._addFileChildren(
    AppReductionProjectsIdRouteChildren,
  )

interface AppReductionProjectsRouteChildren {
  AppReductionProjectsIdRoute: typeof AppReductionProjectsIdRouteWithChildren
  AppReductionProjectsNewRoute: typeof AppReductionProjectsNewRoute
  AppReductionProjectsIndexRoute: typeof AppReductionProjectsIndexRoute
}

const AppReductionProjectsRouteChildren: AppReductionProjectsRouteChildren = {
  AppReductionProjectsIdRoute: AppReductionProjectsIdRouteWithChildren,
  AppReductionProjectsNewRoute: AppReductionProjectsNewRoute,
  AppReductionProjectsIndexRoute: AppReductionProjectsIndexRoute,
}

const AppReductionProjectsRouteWithChildren =
  AppReductionProjectsRoute._addFileChildren(AppReductionProjectsRouteChildren)

interface AppRouteChildren {
  AppCarbonInventoriesRoute: typeof AppCarbonInventoriesRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMyOrganizationRoute: typeof AppMyOrganizationRoute
  AppRecognitionsRoute: typeof AppRecognitionsRoute
  AppReductionPlanRoute: typeof AppReductionPlanRoute
  AppReductionProjectsRoute: typeof AppReductionProjectsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppUserFormRoute: typeof AppUserFormRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCarbonInventoriesRoute: AppCarbonInventoriesRoute,
  AppHomeRoute: AppHomeRoute,
  AppMyOrganizationRoute: AppMyOrganizationRoute,
  AppRecognitionsRoute: AppRecognitionsRoute,
  AppReductionPlanRoute: AppReductionPlanRoute,
  AppReductionProjectsRoute: AppReductionProjectsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppUserFormRoute: AppUserFormRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CarbonInventoryRouteChildren {
  CarbonInventoryIndexRoute: typeof CarbonInventoryIndexRoute
  CarbonInventoryInventoryIdBusinessProfilingRoute: typeof CarbonInventoryInventoryIdBusinessProfilingRoute
  CarbonInventoryInventoryIdEmissionCaptureRoute: typeof CarbonInventoryInventoryIdEmissionCaptureRoute
  CarbonInventoryInventoryIdEmissionResultsRoute: typeof CarbonInventoryInventoryIdEmissionResultsRoute
  CarbonInventoryInventoryIdEmissionSummaryRoute: typeof CarbonInventoryInventoryIdEmissionSummaryRoute
  CarbonInventoryInventoryIdSubcategoryPreselectionRoute: typeof CarbonInventoryInventoryIdSubcategoryPreselectionRoute
}

const CarbonInventoryRouteChildren: CarbonInventoryRouteChildren = {
  CarbonInventoryIndexRoute: CarbonInventoryIndexRoute,
  CarbonInventoryInventoryIdBusinessProfilingRoute:
    CarbonInventoryInventoryIdBusinessProfilingRoute,
  CarbonInventoryInventoryIdEmissionCaptureRoute:
    CarbonInventoryInventoryIdEmissionCaptureRoute,
  CarbonInventoryInventoryIdEmissionResultsRoute:
    CarbonInventoryInventoryIdEmissionResultsRoute,
  CarbonInventoryInventoryIdEmissionSummaryRoute:
    CarbonInventoryInventoryIdEmissionSummaryRoute,
  CarbonInventoryInventoryIdSubcategoryPreselectionRoute:
    CarbonInventoryInventoryIdSubcategoryPreselectionRoute,
}

const CarbonInventoryRouteWithChildren = CarbonInventoryRoute._addFileChildren(
  CarbonInventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CapinautRoute: CapinautRoute,
  CarbonInventoryRoute: CarbonInventoryRouteWithChildren,
  TransparencyRoute: TransparencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
