import { GetAllOrganizationsResponse } from "@repo/types";

const MOCK_DATA: GetAllOrganizationsResponse = {
  total: 156,
  limit: 10,
  offset: 0,
  totalPages: 16,
  hasNext: true,
  hasPrev: false,
  data: [
    {
      id: "1",
      name: "Empresa Demo S.A.",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Transporte y logística",
      subsectorName: "Courier / última milla",
      sizeName: "Mediana",
      status: "ACTIVE",
      isAccredited: true,
      hasCarbonInventories: true,
      lastMeasurement: "2024-11-30T00:00:00Z",
      totalEmissions: 1250,
    },
    {
      id: "2",
      name: "Tech Solutions Ltd.",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Servicios",
      subsectorName: "Servicios profesionales",
      sizeName: "PYME",
      status: "ACTIVE",
      isAccredited: true,
      hasCarbonInventories: false,
      lastMeasurement: null,
      totalEmissions: 0,
    },
    {
      id: "3",
      name: "Retail Global Corp.",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Manufactura",
      subsectorName: "Producción de alimentos",
      sizeName: "Grande",
      status: "ACTIVE",
      isAccredited: true,
      hasCarbonInventories: true,
      lastMeasurement: "2024-11-27T00:00:00Z",
      totalEmissions: 3840,
    },
    {
      id: "4",
      name: "Logística Express",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Construcción",
      subsectorName: "Obras civiles",
      sizeName: "Mediana",
      status: "ACTIVE",
      isAccredited: false,
      hasCarbonInventories: true,
      lastMeasurement: "2024-08-14T00:00:00Z",
      totalEmissions: 890,
    },
    {
      id: "5",
      name: "Alimentos del Sur",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Energía",
      subsectorName: "Generación eléctrica",
      sizeName: "PYME",
      status: "ACTIVE",
      isAccredited: true,
      hasCarbonInventories: true,
      lastMeasurement: "2024-12-09T00:00:00Z",
      totalEmissions: 560,
    },
    {
      id: "6",
      name: "Empresa 6",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Transporte y logística",
      subsectorName: "Logística",
      sizeName: "Grande",
      status: "ACTIVE",
      isAccredited: true,
      hasCarbonInventories: true,
      lastMeasurement: "2024-11-14T00:00:00Z",
      totalEmissions: 958,
    },
    {
      id: "7",
      name: "Empresa 7",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Servicios",
      subsectorName: "Consultoría",
      sizeName: "Mediana",
      status: "ACTIVE",
      isAccredited: true,
      hasCarbonInventories: true,
      lastMeasurement: "2024-11-14T00:00:00Z",
      totalEmissions: 3171,
    },
    {
      id: "8",
      name: "Empresa 8",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Tecnología",
      subsectorName: "Hardware",
      sizeName: "PYME",
      status: "ACTIVE",
      isAccredited: false,
      hasCarbonInventories: false,
      lastMeasurement: null,
      totalEmissions: 0,
    },
    {
      id: "9",
      name: "Empresa 9",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Tecnología",
      subsectorName: "Hardware",
      sizeName: "Mediana",
      status: "ACTIVE",
      isAccredited: false,
      hasCarbonInventories: false,
      lastMeasurement: null,
      totalEmissions: 0,
    },
    {
      id: "10",
      name: "Empresa 10",
      lastSubmissionStatus: null,
      hasUnsubmittedChanges: false,
      sectorName: "Tecnología",
      subsectorName: "Telecomunicaciones",
      sizeName: "Mediana",
      status: "ACTIVE",
      isAccredited: true,
      hasCarbonInventories: false,
      lastMeasurement: null,
      totalEmissions: 0,
    },
  ],
};

export const useAdminOrganizations = (): {
  data: GetAllOrganizationsResponse | undefined;
  isLoading: boolean;
} => {
  return {
    data: MOCK_DATA,
    isLoading: false,
  };
  // return useQuery<GetAllOrganizationsResponse>({
  //   queryKey: [...organizationsKeys.adminAll],
  //   queryFn: () => apiClient.get("/admin/organizations").json(),
  //   staleTime: STALE_TIME_MS,
  //   refetchInterval: REFETCH_INTERVAL_MS,
  // });
};
