const {
  VITE_API_BASE_URL,
  VITE_AZURE_FRONT_CLIENT_ID,
  VITE_AZURE_AUTH_AUTHORITY,
  VITE_FRONT_BASE_URL,
  VITE_AZURE_API_CLIENT_ID,
} = import.meta.env;

export const API_BASE_URL = VITE_API_BASE_URL!;

// Azure External ID Configuration
export const AZURE_FRONT_CLIENT_ID = VITE_AZURE_FRONT_CLIENT_ID!;
export const AZURE_AUTHORITY = VITE_AZURE_AUTH_AUTHORITY!;
export const AZURE_REDIRECT_URI = VITE_FRONT_BASE_URL!;
export const AZURE_API_CLIENT_ID = VITE_AZURE_API_CLIENT_ID!;
